


uname: sky01
#数组
score: {20,30,40}

list: {30.50,60}
list1:
  - 33,
  - 38,
  - 77,
  - 79,
  - 99,

person:
  name: sky
  age: 18
  sex: 0

  person1: {name: jjj, age: 99, sex: 1}

persons:
  - name: sky03,
    age: 18
    sex: 1
  - name: sky02
    age: 99
    sex: 1
#横杠之后有空格
server:
  port: 8081
  servlet:
    path: /sky01
